---
stages:
  - syntax
  - unit
  - notify

variables:
  NOTIFY_ADDRESS: 'frank.brehm@pixelpark.com thomas.dalichow@pixelpark.com'
  SENDER_ADDRESS: 'gitlab-ci@pixelpark.com'
  MODULE_NAME: 'pixelpark-networkmanager'

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# Set `rubygems_version` in the .sync.yml to set a value"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.7-Puppet ~> 6:
  stage: syntax
  image: ruby:2.5.7
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6'
  except:
    - /^dev-.*$/
    - /^dev\/.*$/
    - /^hf.*$/
    - tags

parallel_spec-Ruby 2.5.7-Puppet ~> 6:
  stage: unit
  image: ruby:2.5.7
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6'
  only:
    - master
    - test

parallel_spec-Ruby 2.7.2-Puppet ~> 7:
  stage: unit
  image: ruby:2.7.2
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 7'
  only:
    - master
    - test

Notify Error:
  stage: notify
  allow_failure: true
  when: on_failure
  script: 'echo -e "Error in module ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} (${CI_COMMIT_REF_NAME})\nPlease check ${CI_PROJECT_URL}/pipelines/${CI_PIPELINE_ID}\n\nCommiter: ${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>" | mailx -s "Gitlab-CI error for Puppet module $MODULE_NAME" -r "$SENDER_ADDRESS" "$NOTIFY_ADDRESS"'
  only:
    - master
    - test

# vim: ts=2 et
